### ISSUE TITLE
Read data from an Excel

### ISSUE THREAD

**Issue by JoostGevaert-Arup** [interopxyz/ExcelPlus#6]
Great developments!

Is it also possible to read data from an Excel somehow with this Grasshopper plugin or is that on the road map?

**Comment by interopxyz** [comment]
Hi Joost,
Yes, you should be able to use the Open Workbook component, featured in the
sample file:
ExcelPlus_01-Save_Open.gh

If you are looking to connect to an open Excel file, take a look at
Bumblebee
https://www.food4rhino.com/en/app/bumblebee

**Comment by JoostGevaert-Arup** [comment]
Thanks for the reply!
I tried the basic open part of the ExcelPlus_01-Save_Open.gh script.
I understand that I can retrieve WorkBooks, WorkSheets, Ranges and Cells, but what I don't understand is how to read the values that are in the cells into Grasshopper:
![image](https://github.com/interopxyz/ExcelPlus/assets/75024225/e20a7058-f664-46f6-ad8f-a563454411cc)

**Comment by interopxyz** [comment]
Hi Joost,
You can use the Construct Cell component.
This is a pass-through component that both modifies and returns the value
of a cell.
See attached

**Comment by JoostGevaert-Arup** [comment]
Ah, yes, got it! Amazing! Thanks!

**Comment by interopxyz** [comment]
Great,
I'm still not happy with the name of that component.
Its confusing and may change in a future release.
